- name: install httpd, mod_ssl, php, firewalld
  yum:
    name: [httpd, mod_ssl, php, firewalld]
    state: installed
- name: Manage firewalld service
  systemd:
    name: firewalld
    state: "{{ firewall_enabled | ternary('started','stopped') }}"
    enabled: "{{ firewall_enabled }}"    
- name: configure firewall    
  firewalld:
    service: "{{ item }}"
    permanent: yes
    state: enabled
  with_items:
     - http
     - https
     