- name: install httpd, mod_ssl, php, firewalld
  yum:
    name: [httpd, mod_ssl, php, firewalld]
    state: installed
- name: configure firewall    
  firewalld:
    service: "{{ item }}"
    permanent: yes
    state: enabled
  with_items:
     - http
     - https      