- name: install httpd, mod_ssl, php, firewalld
  yum:
    name: [httpd, mod_ssl, php, firewalld]
    state: installed

- name: Manage firewalld service
  systemd:
    name: firewalld
    state: "{{ firewall_enabled | ternary('started','stopped') }}"
    enabled: "{{ firewall_enabled }}"    

- name: configure firewall    
  firewalld:
    service: "{{ item }}"
    permanent: yes
    state: enabled
  with_items:
     - http
     - https

- name: Apache service is running and enabled on boot
  systemd:
    name: httpd
    state: started
    enabled: yes 

- name: create the file /var/www/html/index.html
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
