---
- name: list facts
  become: yes
  remote_user: automation
  hosts: proxy
  gather_facts: yes
  tasks:
    - name: facts
      debug:
        var: "{{ hostvars[client1.ipa.vm][ansible_all_ipv4_addresses] }}"