---
- name: list facts
  become: yes
  remote_user: automation
  hosts: proxy
  gather_facts: no
  tasks:
    - name: facts
      debug:
        msg: "{{ [client1.ipa.vm[ansible_version]] }}"

    - name: facts variation
      debug:
        msg: "{{ [ansible_version] }}"        

    - name: 10 facts variation
      debug:
        msg: "{{ [ansible_version.string] }}"

  #WRONG  - name: 20 facts variation
  #WRONG    debug:
  #WRONG      msg: "{{ [ansible_version][string] }}"

    - name: 30 facts variation
      debug:
        msg: "{{ [client1.ipa.vm] }}" 

  #WRONG  - name: 40 facts variation
  #WRONG    debug:
  #WRONG      msg: "{{ client1.ipa.vm }}"        

    - name: checkout setup
      setup:
        filter: ansible_*_mb

    - name: display setup variables
      debug:
        msg: "{{ [ansible_facts] }}"        