- name: extract matching keys from a list of dictionaries
  remote_user: automation
  become: yes
  hosts: proxy
  gather_facts: no
  tasks:
    - name: Show extracted list of keys from a list of dictionaries
      ansible.builtin.debug:
        msg: "{{ chainss | map('extract', chains_configg) | map(attribute='configss') | flatten | map(attribute='typee') | flatten }}"
      vars:
        chainss: [1, 2, 3]
        chains_configg:
            1:
                foo: bar
                configss:
                    - typee: routed
                      version: 0.1
                    - typee: bridged
                      version: 0.2
                    - typee: routedd
                      version: 0.1
                    - typee: bridgedd
                      version: 0.2                      
            2:
                foo: baz
                configss:
                    - typee: routed
                      version: 1.0
                    - typee: bridged
                      version: 1.1
            3:
                foo: baz
                configss:
                    - typee: routed
                      version: 1.0
                    - typee: bridged
                      version: 1.1

    - name: Retrieve the list of home directories
      ansible.builtin.command: ls /home
      register: home_dirs

    - name: Add home dirs to the backup spooler
      ansible.builtin.file:
        path: /mnt/bkspool/{{ item }}
        src: /home/{{ item }}
        state: link
      loop: "{{ home_dirs.stdout_lines }}"  