---
- name: Create a symbolic link
  hosts: ipaserver
  remote_user: automation
  gather_facts: no
  become: yes
  tasks:
  - name: Create a symbolic link
    file:
      src: /usr/lib/systemd/system/multi-user.target
      dest: /etc/systemd/system/default.target
      owner: automation
      group: automation
      state: link