---
- name: custom fact
  hosts: proxy
  become: yes
  remote_user: automation
  tasks:
    
    - name: "Create custom fact directory"
      file:
        path: "/etc/ansible/facts.d"
        state: "directory"

    - name: "Create custom fact file"
      template: 
        src: facts.j2
        dest: /etc/ansible/facts.d/custom.fact