---
- name:
  hosts: test
  serial: 1
  tasks:
  - name: 'do something'
    debug: msg='important job'
    notify:
      - restart my service
  post_tasks:
  - name: check if restart pending
    stat: path=/var/run/myservice_restart.pending
    register: myservice_restart
  - name: print myservice_restart
     debug: msg = myservice_restart 
  - name: Restart my service 
    block:
      - service: name=myservice state=restarted
        register: restart_status
        until: restart_status|success
        retries: 30
        delay: 5
      - file: path=/var/run/myservice_restart.pending state=absent
    when: myservice_restart.stat.exists
  handlers:
  - name: restart my service
    file: path=/var/run/myservice_restart.pending state=touch