---
- name: Playbook to handle hosts
  hosts: ipaserver
  vars_files: /home/panicjens/plays/secret.yml
  become: true

  tasks:
  - name: Ensure host host01.example.com is absent
    ipahost:
      name: 2nd.ipa.vm
      update_dns: yes
      state: absent
