---
- name: Host present
  hosts: ipaserver
  vars_files: secret.yml
  become: true

  tasks:
  - name: Ensure host is present
    ipahost:
      ipaadmin_password: 123456789
      name: 3rd.ipa.vm
      description: Example host
      ip_address: 192.168.1.102
      locality: Lab
      ns_host_location: Lab
      ns_os_version: fedora 34
      ns_hardware_platform: Lenovo E585
      mac_address:
      - "00:f4:8d:d6:68:43"
      update_dns: yes
      state: present
