---
- name: register device_info with parted
  hosts: database
  become: yes
  remote_user: automation
  gather_facts: yes
  tasks:
    #- name: facts variation
    #  debug:
    #    msg: "{{ ansible_facts }}"

    - name: register info in device_info
      parted: device=/dev/vdb unit=s
      register: device_info

    - name: show device info
      debug:
        msg: "{{ device_info }}"

    - name: create partition no. 3
      parted:
        unit: MiB
        device: /dev/vdb
       # fs_type: ext4
        number: 3
        part_type: primary
        part_start: 1954.0MiB
        part_end: 3072.0MiB
        state: present

    - name: register info in device_info
      parted: device=/dev/vdb unit=s
      register: device_info

    - name: show device info
      debug:
        msg: "{{ device_info }}"        