---
- name: register device_info with parted
  hosts: database
  become: yes
  remote_user: automation
  gather_facts: yes
  tasks:
    - name: facts variation
      debug:
        msg: "{{ ansible_facts }}"

    - name: register info in device_info
      parted: device=/dev/vdb unit=MiB
      register: device_info

    - name: show device info
      debug:
        msg: "{{ device_info }}"