---
- name: Software Repositories
  hosts: database
  become: yes
  remote_user: automation
  vars:
  vars_files:
    - /home/automation/plays/secret.yml
  tasks:
    - name: Add repository
      yum_repository:
        name: mysql56-community
        description: “MySQL 5.6 YUM Repo”
        baseurl: http://repo.mysql.com/yum/mysql-5.6-community/el/7/x86_64/
        gpgkey: http://repo.mysql.com/RPM-GPG-KEY-mysql
        gpgcheck: yes