---
- name: Create and Use Templates to Create Customised Configuration Files
  hosts: proxy:webservers:database
  become: yes
  remote_user: automation
  tasks:
    - name: print ansible_play_hosts
      template:
        src: server_list_template.j2
        dest: /etc/server_list.txt
      when: inventory_hostname in groups['database']  

    - name: print hostvars tz
      debug:
        msg: "{{ hostvars['ansible_facts']['date_time'] }}"