---
- name: custom fact
  hosts: proxy
  become: yes
  remote_user: automation
  tasks:
    
    - name: "Create custom fact directory"
      file:
        path: "/etc/ansible/facts.d"
        state: "directory"
    
    - name: "Insert custom fact file"
      copy:
        src: /home/automation/plays/custom-fact.sh
        dest: /etc/ansible/facts.d/custom.fact
        mode: 0755