---
- name: Use Conditionals to Control Play Execution
  hosts: proxy
  gather_facts: yes
  become: yes
  remote_user: automation
  tasks:

  - name: 10 display setup variables
    debug:
      msg: "{{ ansible_facts.memory_mb.real.total }}"

  - name: Set vm.swappiness to 59 in /etc/sysctl.conf
    sysctl:
      name: vm.swappiness
      value: '60'
      state: present
    when: ansible_facts.memory_mb.real.total  is greaterthan 2048

  - name: If a server has less than 2048MB of RAM
    debug:
      msg: 'Server memory less than 2048MB'
    when: ansible_facts.memory_mb.real.total  is lessthan 2048  