- name: Create a new primary partition with a size of 1GiB
  parted:
    device: /dev/vdb
    number: 1
    state: present
    part_end: 800MiB  
- name: Create a volume group on top of /dev/vdb1 and resize the volume group /dev/vdb1 to the maximum possible
  lvg:
    vg: vg_database
    pvs: /dev/vdb1
- name: Create a logical volume the size of 512 MB
  lvol:
    vg: vg_database
    lv: lv_mysql
    size: 512m
- name: unmount lv_mysql /mnt/mysql_backups
  mount:
    path: /mnt/mysql_backups
    src: /dev/vg_database/lv_mysql
    fstype: xfs
    state: unmounted
- name: create xfs filesystem
  filesystem:
    dev: /dev/vg_database/lv_mysql
    force: yes
    fstype: xfs
- name: mount lv_mysql /mnt/mysql_backups
  mount:
    path: /mnt/mysql_backups
    src: /dev/vg_database/lv_mysql
    fstype: xfs
    state: mounted
- name: install the latest version of mysql
  yum:
    name: "{{ item }}"
    state: installed
    with item:
      - mysql-community-server
      - PyMySQL
- name: install the latest version of firewalld
  yum:
    name: firewalld
    state: present
- name: Make sure firewalld is running and enabled
  systemd:
    enabled: yes
    state: started
    name: firewalld
- name: enable mysql on firewall
  firewalld:
    service: mysql
    permanent: yes 
    state: enabled
- name: Make sure mysqld is running and enabled
  systemd:
    enabled: yes
    state: started
    name: mysqld
- name: Configure MySQL server configuration file
  template: src=my.cnf.j2 dest=/etc/my.cnf
  tags: mysql
  notify: restart mysql
- name: Make sure there is neither a database with name 'foo', nor one with name 'bar'
  community.mysql.mysql_db:
    name:
      - foo
      - bar
    state: absent                 