- name: Create a new primary partition with a size of 1GiB
  parted:
    device: /dev/vdb
    number: 1
    state: present
    part_end: 800MiB  
- name: Create a volume group on top of /dev/sda3 and resize the volume group /dev/sda3 to the maximum possible
  lvg:
    vg: vg_database
    pvs: /dev/vdb1
- name: Create a logical volume the size of 512 MB
  lvol:
    vg: vg_database
    lv: lv_mysql
    size: 512m
- name: unmount lv_mysql /mnt/mysql_backups
  mount:
    path: /mnt/mysql_backups
    src: /dev/vg_database/lv_mysql
    fstype: xfs
    state: unmounted
- name: create xfs filesystem
  filesystem:
    dev: /dev/vg_database/lv_mysql
    force: yes
    fstype: xfs
- name: mount lv_mysql /mnt/mysql_backups
  mount:
    path: /mnt/mysql_backups
    src: /dev/vg_database/lv_mysql
    fstype: xfs
    state: mounted
- name: install the latest version of mysql
  yum:
    name: mysql-community-server
    state: installed    