galaxy_info:
  author: Thomas Woerner <twoerner@redhat.com>
  description: Configure firewalld and system-config-firewall/lokkit
  company: Red Hat, Inc.
  license: GPLv2+
  min_ansible_version: 2.7
  galaxy_tags: [ 'firewall', 'system' ]
  platforms:
    - name: Fedora
      versions:
        - all
    - name: EL
      versions:
        - 7
        - 8
